services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GeorgRinger\CartStripe\:
    resource: '../Classes/*'

  GeorgRinger\CartStripe\EventListener\Order\Payment\ProviderRedirect:
    arguments:
      $configurationManager: '@TYPO3\CMS\Extbase\Configuration\ConfigurationManager'
      $persistenceManager: '@TYPO3\CMS\Extbase\Persistence\Generic\PersistenceManager'
      $typoScriptService: '@TYPO3\CMS\Core\TypoScript\TypoScriptService'
      $cartRepository: '@Extcode\Cart\Domain\Repository\CartRepository'
    tags:
      - name: event.listener
        identifier: 'cart-stripe--order--payment--provider-redirect'
        event: Extcode\Cart\Event\Order\PaymentEvent

  GeorgRinger\CartStripe\EventListener\Order\Payment\ClearCart:
#    arguments:
#      $cartUtility: '@Extcode\Cart\Utility\CartUtility'
#      $sessionHandler: '@Extcode\Cart\Service\SessionHandler'
    tags:
      - name: event.listener
        identifier: 'cart-stripe--order--payment--clear-cart'
        event: Extcode\Cart\Event\Order\PaymentEvent
        before: 'cart-stripe--order--payment--provider-redirect'
